### ISSUE TITLE
Absent flags during tests leading to hidden elements on mobile UI

### ISSUE THREAD

**Issue by NitWitted** [curio-team/info-website#34]
![image](https://github.com/curio-team/info-website/assets/55002387/9cf3adfd-1f8d-4b11-a146-ec32d49fe17f)
![image](https://github.com/curio-team/info-website/assets/55002387/369c5e06-0790-4845-a352-f509a0f17ed1)

Like the title says, due to the absence of the language flags while testing, it can lead to things like hamburger menus being hidden on mobile layouts without the student's knowledge. This can be fixed by adding the flags in the test site.

**Comment by luttje** [comment]
Closed in #35
